### ISSUE TITLE
Class local variable references do not work anymore

### ISSUE THREAD

**Issue by lukasjarosch** [lukasjarosch/skipper#41]
Given the following class

```yaml
---
names:
  state_resource_group: "rg-${target_name}-terraform"
  state_storage_account: 
    name: "${target_name}terraformstate"
    container_name: ${names:state_resource_group}
```

Using the `state_storage_account.container_name` value results in `<nil>`. 
Absolute referencing still works.
